name: neural_stream
description: A library for neurologically oriented programming
version: 0.0.1
homepage: https://github.com/Jerome-Saltmarsh/event_stream

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.7