name: neural_stream
description: A library for neurologically oriented programming
version: 0.1.0
homepage: https://github.com/Jerome-Saltmarsh/neural_stream

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.8